// <auto-generated />
using System;
using System.Collections.Generic;
using Devv.WebServer.Api.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Devv.WebServer.Api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.ActiveHealthCheckConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("HealthCheckConfigId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Timeout")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckConfigId")
                        .IsUnique();

                    b.ToTable("ActiveHealthChecks");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.CertificateConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwsRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AwsSecretName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyVaultName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyVaultSecretName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyVaultUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RouteConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteConfigId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.ClusterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoadBalancingPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.DestinationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClusterConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HeaderMatchConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Values")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("MatchConfigId");

                    b.ToTable("HeaderMatches");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HealthCheckConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClusterConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("HealthChecks");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HttpClientConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClusterConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("DangerousAcceptAnyServerCertificate")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableMultipleHttp2Connections")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConnectionsPerServer")
                        .HasColumnType("integer");

                    b.Property<string>("RequestHeaderEncoding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseHeaderEncoding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SslProtocols")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("HttpClients");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HttpRequestConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("ActivityTimeout")
                        .HasColumnType("interval");

                    b.Property<bool>("AllowResponseBuffering")
                        .HasColumnType("boolean");

                    b.Property<int>("ClusterConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("HttpRequests");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.MatchConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Hosts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Methods")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RouteConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteConfigId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.MetadataConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClusterConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RouteConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.HasIndex("RouteConfigId")
                        .IsUnique();

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.PassiveHealthCheckConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("HealthCheckConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ReactivationPeriod")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckConfigId")
                        .IsUnique();

                    b.ToTable("PassiveHealthChecks");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.QueryParameterMatchConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Values")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("MatchConfigId");

                    b.ToTable("QueryParameterMatches");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.RouteConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizationPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorsPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("MaxRequestBodySize")
                        .HasColumnType("bigint");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.SessionAffinityConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClusterConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FailurePolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("SessionAffinities");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.TransformConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RequestHeader")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RouteConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RouteConfigId");

                    b.ToTable("Transforms");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.ActiveHealthCheckConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.HealthCheckConfig", "HealthCheckConfig")
                        .WithOne("Active")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.ActiveHealthCheckConfig", "HealthCheckConfigId");

                    b.Navigation("HealthCheckConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.CertificateConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.RouteConfig", "RouteConfig")
                        .WithOne("Certificate")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.CertificateConfig", "RouteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.DestinationConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.ClusterConfig", "ClusterConfig")
                        .WithMany("Destinations")
                        .HasForeignKey("ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HeaderMatchConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.MatchConfig", "MatchConfig")
                        .WithMany("Headers")
                        .HasForeignKey("MatchConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HealthCheckConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.ClusterConfig", "ClusterConfig")
                        .WithOne("HealthCheck")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.HealthCheckConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HttpClientConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.ClusterConfig", "ClusterConfig")
                        .WithOne("HttpClient")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.HttpClientConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HttpRequestConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.ClusterConfig", "ClusterConfig")
                        .WithOne("HttpRequest")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.HttpRequestConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.MatchConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.RouteConfig", "RouteConfig")
                        .WithOne("Match")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.MatchConfig", "RouteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.MetadataConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.ClusterConfig", "ClusterConfig")
                        .WithOne("Metadata")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.MetadataConfig", "ClusterConfigId");

                    b.HasOne("Devv.WebServer.Api.Data.Entities.RouteConfig", "RouteConfig")
                        .WithOne("Metadata")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.MetadataConfig", "RouteConfigId");

                    b.Navigation("ClusterConfig");

                    b.Navigation("RouteConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.PassiveHealthCheckConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.HealthCheckConfig", "HealthCheckConfig")
                        .WithOne("Passive")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.PassiveHealthCheckConfig", "HealthCheckConfigId");

                    b.Navigation("HealthCheckConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.QueryParameterMatchConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.MatchConfig", "MatchConfig")
                        .WithMany("QueryParameters")
                        .HasForeignKey("MatchConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.SessionAffinityConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.ClusterConfig", "ClusterConfig")
                        .WithOne("SessionAffinity")
                        .HasForeignKey("Devv.WebServer.Api.Data.Entities.SessionAffinityConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.TransformConfig", b =>
                {
                    b.HasOne("Devv.WebServer.Api.Data.Entities.RouteConfig", "RouteConfig")
                        .WithMany("Transforms")
                        .HasForeignKey("RouteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteConfig");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.ClusterConfig", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("HealthCheck")
                        .IsRequired();

                    b.Navigation("HttpClient")
                        .IsRequired();

                    b.Navigation("HttpRequest")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("SessionAffinity")
                        .IsRequired();
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.HealthCheckConfig", b =>
                {
                    b.Navigation("Active");

                    b.Navigation("Passive");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.MatchConfig", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("QueryParameters");
                });

            modelBuilder.Entity("Devv.WebServer.Api.Data.Entities.RouteConfig", b =>
                {
                    b.Navigation("Certificate")
                        .IsRequired();

                    b.Navigation("Match")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Transforms");
                });
#pragma warning restore 612, 618
        }
    }
}
